# Site settings
title: Jason Etcovitch
email: jasonetco@gmail.com
description: "Jason Etcovitch, Toronto-based Graphic Designer and Web Developer. Feel free to contact me if you have an interesting project, or just want to chat about design!"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jasonet.co" # the base hostname & protocol for your site

imagepath: "/assets/case-studies/{{ page.shortname }}/{{ page.shortname }}"

github_username:  jasonetco

# Build settings
markdown: kramdown

permalink: /:title/

exclude: [
	.gitignore,
	Gruntfile.js,
	Gemfile.lock,
	node_modules/,
	package.json,
	README.md,
	LICENSE
]

sass:
  style: :compressed

gems:
 - jekyll-sitemap