# Site settings
title: Type-Texts
email: jasonetco@gmail.com
description: "Intelligent writings by brilliant people."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jasonet.co" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: /articles/:title/

exclude: [
	.gitignore,
	Gruntfile.js,
	Gemfile.lock,
	node_modules/,
	package.json,
	README.md,
	LICENSE
]

sass:
  style: :compressed

gems:
 - jekyll-sitemap